# This is a basic workflow to help me automate the build, test, and deployment of a Javascript hello-world application
name: Deployment Workflow

on:
  push:
    branches:
    - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Application
      run: |
        npm install
        npm run build

    - name: Test Application
      run: |
        npm run test

    - name: Deploy to Kubernetes Cluster
      uses: bacongobbler/kubectl-action@v2
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
      with:
        args: apply -f k8s

#The workflow checks out the code from the Github repository, builds the application using npm, runs the test for the application, 
#and then deploys it to a Kubernetes cluster using the kubectl-action Github action.
