# This is a basic workflow to help me automate the build, test, and deployment of a Javascript hello-world application
name: Deployment Workflow

on:
  push:
    branches:
    - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Application
      run: |
        npm install
        npm run build

    - name: Test Application
      run: |
        npm run test

    - name: Deploy to Kubernetes
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: myregistry.com/hello-world

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Connect to the Kubernetes cluster
      run: |
        kubectl config use-context my-cluster-context

    - name: Install Helm chart
      run: |
        helm install my-chart .

    - name: Verify resources
      run: |
        kubectl get deployment,service,configmap,secret

    - name: Check logs
      run: |
        kubectl logs $(kubectl get pods -l app=hello-world -o jsonpath="{.items[0].metadata.name}")


#The workflow checks out the code from the Github repository, builds the application using npm, runs the test for the application, 
#and then deploys it to a Kubernetes cluster using the kubectl-action Github action.
